// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticlepageDocumentDataSlicesSlice = ArticleSectionSlice | NewsletterSlice;

/**
 * Content for ArticlePage documents
 */
interface ArticlepageDocumentData {
  /**
   * Slice Zone field in *ArticlePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articlepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticlepageDocumentDataSlicesSlice> /**
   * Meta Description field in *ArticlePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articlepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ArticlePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articlepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *ArticlePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articlepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * ArticlePage document from Prismic
 *
 * - **API ID**: `articlepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticlepageDocumentData>,
    "articlepage",
    Lang
  >;

type ArtistpageDocumentDataSlicesSlice =
  | YoutubeEmbedSlice
  | ArtistSectionSlice
  | ReleasesSlice;

/**
 * Content for ArtistPage documents
 */
interface ArtistpageDocumentData {
  /**
   * Slice Zone field in *ArtistPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: artistpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArtistpageDocumentDataSlicesSlice> /**
   * Meta Description field in *ArtistPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: artistpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ArtistPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artistpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *ArtistPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: artistpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * ArtistPage document from Prismic
 *
 * - **API ID**: `artistpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArtistpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArtistpageDocumentData>,
    "artistpage",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | BannerSlice
  | HeroSlice
  | LabelIntroductionSlice
  | ArtistsSlice
  | SpotlightSlice
  | NewsletterSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | BrandAssetsSectionSlice
  | NewsletterSlice
  | ArtistsSectionSlice
  | BannerSlice
  | LabelSectionSlice
  | BookingSectionSlice
  | ContactSectionSlice
  | BlogSectionSlice
  | PublishingSectionSlice
  | PrivacySectionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Social Navigation*
 */
export interface SettingsDocumentDataSocialNavigationItem {
  /**
   * Label field in *Settings → Social Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Icon field in *Settings → Social Navigation*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_navigation[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Settings → Social Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Monogram field in *Settings → Social Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_navigation[].monogram
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  monogram: prismic.KeyTextField;
}

/**
 * Item in *Settings → Footer Navigation Socials*
 */
export interface SettingsDocumentDataFooterNavigationSocialsItem {
  /**
   * Icon field in *Settings → Footer Navigation Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_socials[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Label field in *Settings → Footer Navigation Socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_socials[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Footer Navigation Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Footer Navigation more*
 */
export interface SettingsDocumentDataFooterNavigationMoreItem {
  /**
   * Label field in *Settings → Footer Navigation more*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_more[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Footer Navigation more*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_more[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Settings → Legal*
 */
export interface SettingsDocumentDataLegalItem {
  /**
   * Label field in *Settings → Legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Legal*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Icon field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_icon: prismic.ImageField<never>;

  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Site Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Social Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_navigation: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialNavigationItem>
  >;

  /**
   * Footer Navigation Socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_navigation_socials: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavigationSocialsItem>
  >;

  /**
   * Footer Navigation more field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation_more[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_navigation_more: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterNavigationMoreItem>
  >;

  /**
   * Legal field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.legal[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  legal: prismic.GroupField<Simplify<SettingsDocumentDataLegalItem>>;

  /**
   * Copyright field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ArticlepageDocument
  | ArtistpageDocument
  | HomepageDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *ArticleSection → Primary*
 */
export interface ArticleSectionSliceDefaultPrimary {
  /**
   * Heading field in *ArticleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Sub Heading field in *ArticleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_heading: prismic.KeyTextField;

  /**
   * Author field in *ArticleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Date field in *ArticleSection → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Category field in *ArticleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Sub Category field in *ArticleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.sub_category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_category: prismic.KeyTextField;

  /**
   * Duration field in *ArticleSection → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.duration
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  duration: prismic.NumberField;

  /**
   * Image field in *ArticleSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Text Content field in *ArticleSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.text_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_content: prismic.RichTextField;

  /**
   * Label field in *ArticleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *ArticleSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: article_section.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for ArticleSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ArticleSection*
 */
type ArticleSectionSliceVariation = ArticleSectionSliceDefault;

/**
 * ArticleSection Shared Slice
 *
 * - **API ID**: `article_section`
 * - **Description**: ArticleSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSectionSlice = prismic.SharedSlice<
  "article_section",
  ArticleSectionSliceVariation
>;

/**
 * Primary content in *ArtistSection → Primary*
 */
export interface ArtistSectionSliceDefaultPrimary {
  /**
   * Heading field in *ArtistSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Image field in *ArtistSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *ArtistSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Biography field in *ArtistSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.biography
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  biography: prismic.RichTextField;

  /**
   * Email field in *ArtistSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.email
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField;

  /**
   * Booking Button field in *ArtistSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.booking_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  booking_button: prismic.KeyTextField;

  /**
   * Label field in *ArtistSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.primary.label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;
}

/**
 * Primary content in *ArtistSection → Items*
 */
export interface ArtistSectionSliceDefaultItem {
  /**
   * Platform Link field in *ArtistSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.items[].platform_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  platform_link: prismic.LinkField;

  /**
   * Platform Icon field in *ArtistSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artist_section.items[].platform_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  platform_icon: prismic.ImageField<never>;
}

/**
 * Default variation for ArtistSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtistSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArtistSectionSliceDefaultPrimary>,
  Simplify<ArtistSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ArtistSection*
 */
type ArtistSectionSliceVariation = ArtistSectionSliceDefault;

/**
 * ArtistSection Shared Slice
 *
 * - **API ID**: `artist_section`
 * - **Description**: ArtistSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtistSectionSlice = prismic.SharedSlice<
  "artist_section",
  ArtistSectionSliceVariation
>;

/**
 * Primary content in *Showroll → Primary*
 */
export interface ArtistsSliceDefaultPrimary {
  /**
   * Heading field in *Showroll → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artists.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Showroll → Items*
 */
export interface ArtistsSliceDefaultItem {
  /**
   * Name field in *Showroll → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artists.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * PageLink field in *Showroll → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: artists.items[].pagelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  pagelink: prismic.LinkField;

  /**
   * Preview field in *Showroll → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artists.items[].preview
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  preview: prismic.ImageField<never>;
}

/**
 * Default variation for Showroll Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtistsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArtistsSliceDefaultPrimary>,
  Simplify<ArtistsSliceDefaultItem>
>;

/**
 * Slice variation for *Showroll*
 */
type ArtistsSliceVariation = ArtistsSliceDefault;

/**
 * Showroll Shared Slice
 *
 * - **API ID**: `artists`
 * - **Description**: Artists
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtistsSlice = prismic.SharedSlice<
  "artists",
  ArtistsSliceVariation
>;

/**
 * Primary content in *ArtistsSection → Primary*
 */
export interface ArtistsSectionSliceDefaultPrimary {
  /**
   * Heading field in *ArtistsSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artists_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *ArtistsSection → Items*
 */
export interface ArtistsSectionSliceDefaultItem {
  /**
   * Artist Image field in *ArtistsSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: artists_section.items[].artist_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  artist_image: prismic.ImageField<never>;

  /**
   * Artist Type field in *ArtistsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artists_section.items[].artist_type
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  artist_type: prismic.RichTextField;

  /**
   * Artist Name field in *ArtistsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artists_section.items[].artist_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  artist_name: prismic.RichTextField;

  /**
   * Label field in *ArtistsSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: artists_section.items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Page Link field in *ArtistsSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: artists_section.items[].page_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_link: prismic.ContentRelationshipField;
}

/**
 * Default variation for ArtistsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtistsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArtistsSectionSliceDefaultPrimary>,
  Simplify<ArtistsSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ArtistsSection*
 */
type ArtistsSectionSliceVariation = ArtistsSectionSliceDefault;

/**
 * ArtistsSection Shared Slice
 *
 * - **API ID**: `artists_section`
 * - **Description**: ArtistsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArtistsSectionSlice = prismic.SharedSlice<
  "artists_section",
  ArtistsSectionSliceVariation
>;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Heading field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Button Label field in *Banner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BlogSection → Primary*
 */
export interface BlogSectionSliceDefaultPrimary {
  /**
   * Heading field in *BlogSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *BlogSection → Items*
 */
export interface BlogSectionSliceDefaultItem {
  /**
   * Title field in *BlogSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *BlogSection → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Image field in *BlogSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *BlogSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_section.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;
}

/**
 * Default variation for BlogSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSectionSliceDefaultPrimary>,
  Simplify<BlogSectionSliceDefaultItem>
>;

/**
 * Slice variation for *BlogSection*
 */
type BlogSectionSliceVariation = BlogSectionSliceDefault;

/**
 * BlogSection Shared Slice
 *
 * - **API ID**: `blog_section`
 * - **Description**: BlogSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSectionSlice = prismic.SharedSlice<
  "blog_section",
  BlogSectionSliceVariation
>;

/**
 * Primary content in *BookingSection → Primary*
 */
export interface BookingSectionSliceDefaultPrimary {
  /**
   * Heading field in *BookingSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Past Event field in *BookingSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.primary.past_event
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  past_event: prismic.KeyTextField;

  /**
   * Upcoming Event field in *BookingSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.primary.upcoming_event
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  upcoming_event: prismic.KeyTextField;
}

/**
 * Primary content in *BookingSection → Items*
 */
export interface BookingSectionSliceDefaultItem {
  /**
   * Date field in *BookingSection → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Place Name field in *BookingSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].place_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  place_name: prismic.KeyTextField;

  /**
   * City Country field in *BookingSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].city_country
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city_country: prismic.KeyTextField;

  /**
   * Artist Page field in *BookingSection → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].artist_page
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  artist_page: prismic.ContentRelationshipField<"artistpage">;

  /**
   * Artist Name field in *BookingSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].artist_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist_name: prismic.KeyTextField;

  /**
   * Link field in *BookingSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * TBA field in *BookingSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: booking_section.items[].tba
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tba: prismic.KeyTextField;
}

/**
 * Default variation for BookingSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookingSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookingSectionSliceDefaultPrimary>,
  Simplify<BookingSectionSliceDefaultItem>
>;

/**
 * Slice variation for *BookingSection*
 */
type BookingSectionSliceVariation = BookingSectionSliceDefault;

/**
 * BookingSection Shared Slice
 *
 * - **API ID**: `booking_section`
 * - **Description**: BookingSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookingSectionSlice = prismic.SharedSlice<
  "booking_section",
  BookingSectionSliceVariation
>;

/**
 * Primary content in *BrandAssetsSection → Primary*
 */
export interface BrandAssetsSectionSliceDefaultPrimary {
  /**
   * Heading field in *BrandAssetsSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brand_assets_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for BrandAssetsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandAssetsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrandAssetsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrandAssetsSection*
 */
type BrandAssetsSectionSliceVariation = BrandAssetsSectionSliceDefault;

/**
 * BrandAssetsSection Shared Slice
 *
 * - **API ID**: `brand_assets_section`
 * - **Description**: BrandAssetsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrandAssetsSectionSlice = prismic.SharedSlice<
  "brand_assets_section",
  BrandAssetsSectionSliceVariation
>;

/**
 * Primary content in *ContactSection → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Heading field in *ContactSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *ContactSection → Items*
 */
export interface ContactSectionSliceDefaultItem {
  /**
   * Type field in *ContactSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].type
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  type: prismic.RichTextField;

  /**
   * Email field in *ContactSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].email
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField;

  /**
   * Label field in *ContactSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  Simplify<ContactSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Logo field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Icon field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Icon Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.icon_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon_link: prismic.LinkField;

  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *Hero → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Intro → Primary*
 */
export interface LabelIntroductionSliceDefaultPrimary {
  /**
   * Heading field in *Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: label_introduction.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Quote field in *Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: label_introduction.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;

  /**
   * Text field in *Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: label_introduction.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * EasterEggLink field in *Intro → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: label_introduction.primary.easteregglink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  easteregglink: prismic.LinkField;
}

/**
 * Default variation for Intro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LabelIntroductionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LabelIntroductionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Intro*
 */
type LabelIntroductionSliceVariation = LabelIntroductionSliceDefault;

/**
 * Intro Shared Slice
 *
 * - **API ID**: `label_introduction`
 * - **Description**: LabelIntroduction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LabelIntroductionSlice = prismic.SharedSlice<
  "label_introduction",
  LabelIntroductionSliceVariation
>;

/**
 * Primary content in *LabelSection → Primary*
 */
export interface LabelSectionSliceDefaultPrimary {
  /**
   * Heading field in *LabelSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: label_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for LabelSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LabelSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LabelSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LabelSection*
 */
type LabelSectionSliceVariation = LabelSectionSliceDefault;

/**
 * LabelSection Shared Slice
 *
 * - **API ID**: `label_section`
 * - **Description**: LabelSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LabelSectionSlice = prismic.SharedSlice<
  "label_section",
  LabelSectionSliceVariation
>;

/**
 * Primary content in *Newsletter → Primary*
 */
export interface NewsletterSliceDefaultPrimary {
  /**
   * Heading field in *Newsletter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Label field in *Newsletter → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Default variation for Newsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Newsletter*
 */
type NewsletterSliceVariation = NewsletterSliceDefault;

/**
 * Newsletter Shared Slice
 *
 * - **API ID**: `newsletter`
 * - **Description**: Newsletter
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSlice = prismic.SharedSlice<
  "newsletter",
  NewsletterSliceVariation
>;

/**
 * Primary content in *PrivacySection → Primary*
 */
export interface PrivacySectionSliceDefaultPrimary {
  /**
   * Heading field in *PrivacySection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: privacy_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for PrivacySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrivacySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PrivacySection*
 */
type PrivacySectionSliceVariation = PrivacySectionSliceDefault;

/**
 * PrivacySection Shared Slice
 *
 * - **API ID**: `privacy_section`
 * - **Description**: PrivacySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PrivacySectionSlice = prismic.SharedSlice<
  "privacy_section",
  PrivacySectionSliceVariation
>;

/**
 * Primary content in *PublishingSection → Primary*
 */
export interface PublishingSectionSliceDefaultPrimary {
  /**
   * Heading field in *PublishingSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: publishing_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for PublishingSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PublishingSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PublishingSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PublishingSection*
 */
type PublishingSectionSliceVariation = PublishingSectionSliceDefault;

/**
 * PublishingSection Shared Slice
 *
 * - **API ID**: `publishing_section`
 * - **Description**: PublishingSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PublishingSectionSlice = prismic.SharedSlice<
  "publishing_section",
  PublishingSectionSliceVariation
>;

/**
 * Primary content in *Releases → Primary*
 */
export interface ReleasesSliceDefaultPrimary {
  /**
   * Heading field in *Releases → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Releases → Items*
 */
export interface ReleasesSliceDefaultItem {
  /**
   * Cover field in *Releases → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * Label field in *Releases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Release Album field in *Releases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].release_album
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  release_album: prismic.RichTextField;

  /**
   * Release EP field in *Releases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].release_ep
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  release_ep: prismic.RichTextField;

  /**
   * Release Single field in *Releases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].release_single
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  release_single: prismic.RichTextField;

  /**
   * Release Title field in *Releases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].release_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  release_title: prismic.RichTextField;

  /**
   * Link field in *Releases → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Releases Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReleasesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReleasesSliceDefaultPrimary>,
  Simplify<ReleasesSliceDefaultItem>
>;

/**
 * Slice variation for *Releases*
 */
type ReleasesSliceVariation = ReleasesSliceDefault;

/**
 * Releases Shared Slice
 *
 * - **API ID**: `releases`
 * - **Description**: Releases
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReleasesSlice = prismic.SharedSlice<
  "releases",
  ReleasesSliceVariation
>;

/**
 * Primary content in *Spotlight → Primary*
 */
export interface SpotlightSliceDefaultPrimary {
  /**
   * Heading field in *Spotlight → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *Spotlight → Items*
 */
export interface SpotlightSliceDefaultItem {
  /**
   * Single Release field in *Spotlight → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].single_release
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  single_release: prismic.RichTextField;

  /**
   * EP Release field in *Spotlight → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].ep_release
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ep_release: prismic.RichTextField;

  /**
   * Album Release field in *Spotlight → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].album_release
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  album_release: prismic.RichTextField;

  /**
   * Year field in *Spotlight → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].year
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  year: prismic.RichTextField;

  /**
   * Title field in *Spotlight → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * ArtistName field in *Spotlight → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].artistname
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  artistname: prismic.RichTextField;

  /**
   * Link field in *Spotlight → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Spotlight → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Cover field in *Spotlight → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: spotlight.items[].cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;
}

/**
 * Default variation for Spotlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpotlightSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpotlightSliceDefaultPrimary>,
  Simplify<SpotlightSliceDefaultItem>
>;

/**
 * Slice variation for *Spotlight*
 */
type SpotlightSliceVariation = SpotlightSliceDefault;

/**
 * Spotlight Shared Slice
 *
 * - **API ID**: `spotlight`
 * - **Description**: Spotlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SpotlightSlice = prismic.SharedSlice<
  "spotlight",
  SpotlightSliceVariation
>;

/**
 * Primary content in *StudioSection → Primary*
 */
export interface StudioSectionSliceDefaultPrimary {
  /**
   * Heading field in *StudioSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: studio_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for StudioSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudioSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StudioSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StudioSection*
 */
type StudioSectionSliceVariation = StudioSectionSliceDefault;

/**
 * StudioSection Shared Slice
 *
 * - **API ID**: `studio_section`
 * - **Description**: StudioSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StudioSectionSlice = prismic.SharedSlice<
  "studio_section",
  StudioSectionSliceVariation
>;

/**
 * Primary content in *YoutubeEmbed → Primary*
 */
export interface YoutubeEmbedSliceDefaultPrimary {
  /**
   * Heading field in *YoutubeEmbed → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_embed.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *YoutubeEmbed → Items*
 */
export interface YoutubeEmbedSliceDefaultItem {
  /**
   * Youtube ID field in *YoutubeEmbed → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: youtube_embed.items[].youtubeID
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  youtubeID: prismic.KeyTextField;
}

/**
 * Default variation for YoutubeEmbed Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YoutubeEmbedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<YoutubeEmbedSliceDefaultPrimary>,
  Simplify<YoutubeEmbedSliceDefaultItem>
>;

/**
 * Slice variation for *YoutubeEmbed*
 */
type YoutubeEmbedSliceVariation = YoutubeEmbedSliceDefault;

/**
 * YoutubeEmbed Shared Slice
 *
 * - **API ID**: `youtube_embed`
 * - **Description**: YoutubeEmbed
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type YoutubeEmbedSlice = prismic.SharedSlice<
  "youtube_embed",
  YoutubeEmbedSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticlepageDocument,
      ArticlepageDocumentData,
      ArticlepageDocumentDataSlicesSlice,
      ArtistpageDocument,
      ArtistpageDocumentData,
      ArtistpageDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataSocialNavigationItem,
      SettingsDocumentDataFooterNavigationSocialsItem,
      SettingsDocumentDataFooterNavigationMoreItem,
      SettingsDocumentDataLegalItem,
      AllDocumentTypes,
      ArticleSectionSlice,
      ArticleSectionSliceDefaultPrimary,
      ArticleSectionSliceVariation,
      ArticleSectionSliceDefault,
      ArtistSectionSlice,
      ArtistSectionSliceDefaultPrimary,
      ArtistSectionSliceDefaultItem,
      ArtistSectionSliceVariation,
      ArtistSectionSliceDefault,
      ArtistsSlice,
      ArtistsSliceDefaultPrimary,
      ArtistsSliceDefaultItem,
      ArtistsSliceVariation,
      ArtistsSliceDefault,
      ArtistsSectionSlice,
      ArtistsSectionSliceDefaultPrimary,
      ArtistsSectionSliceDefaultItem,
      ArtistsSectionSliceVariation,
      ArtistsSectionSliceDefault,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BlogSectionSlice,
      BlogSectionSliceDefaultPrimary,
      BlogSectionSliceDefaultItem,
      BlogSectionSliceVariation,
      BlogSectionSliceDefault,
      BookingSectionSlice,
      BookingSectionSliceDefaultPrimary,
      BookingSectionSliceDefaultItem,
      BookingSectionSliceVariation,
      BookingSectionSliceDefault,
      BrandAssetsSectionSlice,
      BrandAssetsSectionSliceDefaultPrimary,
      BrandAssetsSectionSliceVariation,
      BrandAssetsSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceDefaultItem,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      LabelIntroductionSlice,
      LabelIntroductionSliceDefaultPrimary,
      LabelIntroductionSliceVariation,
      LabelIntroductionSliceDefault,
      LabelSectionSlice,
      LabelSectionSliceDefaultPrimary,
      LabelSectionSliceVariation,
      LabelSectionSliceDefault,
      NewsletterSlice,
      NewsletterSliceDefaultPrimary,
      NewsletterSliceVariation,
      NewsletterSliceDefault,
      PrivacySectionSlice,
      PrivacySectionSliceDefaultPrimary,
      PrivacySectionSliceVariation,
      PrivacySectionSliceDefault,
      PublishingSectionSlice,
      PublishingSectionSliceDefaultPrimary,
      PublishingSectionSliceVariation,
      PublishingSectionSliceDefault,
      ReleasesSlice,
      ReleasesSliceDefaultPrimary,
      ReleasesSliceDefaultItem,
      ReleasesSliceVariation,
      ReleasesSliceDefault,
      SpotlightSlice,
      SpotlightSliceDefaultPrimary,
      SpotlightSliceDefaultItem,
      SpotlightSliceVariation,
      SpotlightSliceDefault,
      StudioSectionSlice,
      StudioSectionSliceDefaultPrimary,
      StudioSectionSliceVariation,
      StudioSectionSliceDefault,
      YoutubeEmbedSlice,
      YoutubeEmbedSliceDefaultPrimary,
      YoutubeEmbedSliceDefaultItem,
      YoutubeEmbedSliceVariation,
      YoutubeEmbedSliceDefault,
    };
  }
}
