// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_section: dynamic(() => import("./ArticleSection")),
  artist_section: dynamic(() => import("./ArtistSection")),
  artists: dynamic(() => import("./Showroll")),
  artists_section: dynamic(() => import("./ArtistsSection")),
  banner: dynamic(() => import("./Banner")),
  blog_section: dynamic(() => import("./BlogSection")),
  booking_section: dynamic(() => import("./BookingSection")),
  brand_assets_section: dynamic(() => import("./BrandAssetsSection")),
  contact_section: dynamic(() => import("./ContactSection")),
  hero: dynamic(() => import("./Hero")),
  label_introduction: dynamic(() => import("./Intro")),
  label_section: dynamic(() => import("./LabelSection")),
  newsletter: dynamic(() => import("./Newsletter")),
  privacy_section: dynamic(() => import("./PrivacySection")),
  publishing_section: dynamic(() => import("./PublishingSection")),
  releases: dynamic(() => import("./Releases")),
  spotlight: dynamic(() => import("./Spotlight")),
  studio_section: dynamic(() => import("./StudioSection")),
  youtube_embed: dynamic(() => import("./YoutubeEmbed")),
};
